### ISSUE TITLE
два warring после монтирования компонента

### ISSUE THREAD

**Issue by serjo96** [z4o4z/react-dribble-button#2]
Warning: Failed prop type: ReactDribbleButton: prop type `children` is invalid; it must be a function, usually from React.PropTypes.
    in ReactDribbleButton (created by Jss(ReactDribbleButton))

Warning: Unknown props `sheet`, `animationDuration` on <button> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in button (created by ReactDribbleButton)

` <DribbleButton color="deep-purple" onClick={() => this.setState({imgCount: this.state.imgCount += 12})} animationDuration={1000} >Больше</DribbleButton>`

**Comment by z4o4z** [comment]
Fixed in the v0.2.2

**Comment by serjo96** [comment]
Обновился до "react-dribble-button": "^0.2.2",
Первой ошибки больше нет, но ошибка по поводу не известного пропса `sheet` осталась.

Warning: Unknown prop `sheet` on <button> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in button (created by ReactDribbleButton)
